// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Waggo.Infrastructure.Persistence.Context;

#nullable disable

namespace Waggo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WaggoDbContext))]
    [Migration("20260930082006_AddWalkMessages")]
    partial class AddWalkMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Waggo.Domain.Entities.Messaging.WalkMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("SentBy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("sent_by");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.Property<Guid>("WalkId")
                        .HasColumnType("uuid")
                        .HasColumnName("walk_id");

                    b.HasKey("Id")
                        .HasName("pk_walk_messages");

                    b.HasIndex("WalkId", "SentAt")
                        .HasDatabaseName("ix_walk_messages_walk_id_sent_at");

                    b.ToTable("walk_messages", "messaging");
                });

            modelBuilder.Entity("Waggo.Domain.Entities.Pets.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Breed")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("breed");

                    b.Property<string>("MedicalNotes")
                        .HasColumnType("text")
                        .HasColumnName("medical_notes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("size");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_pets");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_pets_owner_id");

                    b.ToTable("pets", "pets");
                });

            modelBuilder.Entity("Waggo.Domain.Entities.Tracking.TrackPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("WalkId")
                        .HasColumnType("uuid")
                        .HasColumnName("walk_id");

                    b.HasKey("Id")
                        .HasName("pk_track_points");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_track_points_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("ix_track_points_recorded_at");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RecordedAt"), "brin");

                    b.HasIndex("WalkId")
                        .HasDatabaseName("ix_track_points_walk_id");

                    b.ToTable("track_points", "tracking");
                });

            modelBuilder.Entity("Waggo.Domain.Entities.Tracking.WalkAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<string>("RaisedBy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("raised_by");

                    b.Property<Guid>("WalkId")
                        .HasColumnType("uuid")
                        .HasColumnName("walk_id");

                    b.HasKey("Id")
                        .HasName("pk_walk_alerts");

                    b.HasIndex("WalkId")
                        .HasDatabaseName("ix_walk_alerts_walk_id");

                    b.ToTable("walk_alerts", "tracking");
                });

            modelBuilder.Entity("Waggo.Domain.Entities.Walks.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<decimal>("Commission")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("commission");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_id");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("pickup_address");

                    b.Property<Point>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("pickup_location");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("WalkType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("walk_type");

                    b.Property<string>("WalkerId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("walker_id");

                    b.Property<decimal>("WalkerPayout")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("walker_payout");

                    b.PrimitiveCollection<List<Guid>>("_petIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("pet_ids");

                    b.HasKey("Id")
                        .HasName("pk_walks");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_walks_owner_id");

                    b.HasIndex("PickupLocation")
                        .HasDatabaseName("ix_walks_pickup_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PickupLocation"), "gist");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_walks_status");

                    b.HasIndex("WalkerId")
                        .HasDatabaseName("ix_walks_walker_id");

                    b.ToTable("walks", "walks");
                });
#pragma warning restore 612, 618
        }
    }
}
